/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup1;
import java.awt.Component;
import javax.swing.*;
import java.sql.*;
import logins.*;

/**
 *
 * @author shadrak
 */
public class signup extends javax.swing.JFrame {
    //Connection con = null;
    PreparedStatement p = null,stmt = null;
    //ResultSet q = null;
    Connection con = MySqlconnect.ConnectDB();
    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }
    
   // void initComponents(){
        
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(722, 598));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(182, 93, 45, 21);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(182, 141, 78, 21);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel3.setText("Email-ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(182, 193, 72, 21);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel4.setText("Branch");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(182, 241, 57, 21);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel5.setText("Sex");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(185, 343, 27, 21);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel6.setText("Contact no.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(185, 389, 87, 21);

        Name.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        Name.setText("Firstname Lastname");
        Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameMouseClicked(evt);
            }
        });
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(355, 88, 245, 30);

        username.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        username.setText("anil222");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(355, 136, 245, 30);

        email.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        email.setText("e.g. dev@gmail.com");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(355, 188, 245, 30);

        branch.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        branch.setText("e.g Computer Science");
        branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                branchMouseClicked(evt);
            }
        });
        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });
        getContentPane().add(branch);
        branch.setBounds(355, 236, 272, 30);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Century Schoolbook L", 1, 15)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(355, 340, 64, 26);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Century Schoolbook L", 1, 15)); // NOI18N
        female.setText("Female");
        getContentPane().add(female);
        female.setBounds(453, 340, 83, 26);

        phone.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        phone.setText("eg. 9876543210");
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(355, 384, 150, 30);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(185, 432, 75, 21);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(185, 482, 143, 21);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(355, 432, 170, 28);
        getContentPane().add(confirmpassword);
        confirmpassword.setBounds(355, 478, 170, 28);

        jButton1.setBackground(new java.awt.Color(80, 229, 66));
        jButton1.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(276, 524, 124, 41);

        jLabel10.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel10.setText("Address(City)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(182, 289, 104, 21);

        address.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        address.setText("e.g. Andheri");
        address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressMouseClicked(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(355, 284, 169, 30);

        jLabel11.setFont(new java.awt.Font("Century Schoolbook L", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 84, 200));
        jLabel11.setText("New Membership");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(264, 18, 209, 33);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook L", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(243, 24, 24));
        jLabel12.setText("Atleast 10 Characters..");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(537, 439, 122, 16);

        jButton2.setBackground(new java.awt.Color(235, 157, 71));
        jButton2.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(27, 12, 70, 33);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/buyerspagebackground.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-1, -2, 720, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameActionPerformed

    private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String query1 = "insert into PERSON (NAME,USERNAME,BRANCH,CITY,PASSWORD,SEX) values(?,?,?,?,?,?)";
        String query2 = "insert into CONTACT_DETAILS (P_ID,MOBILE_NO,EMAIL_ID) values(?,?,?)";
        try{
        String pass,cpass;
        
        pass = password.getText();
        cpass = confirmpassword.getText();
        if(pass.equals(cpass)){
        
        p = con.prepareStatement(query1);
        stmt = con.prepareStatement(query2);
        p.setString(1,Name.getText());
        stmt.setString(1,username.getText());
        p.setString(3,branch.getText());
        stmt.setString(3,email.getText());
        p.setString(2,username.getText());
        p.setString(4,address.getText());
        //p.setString(6,year.getText());
        if(male.isSelected()){
            p.setString(6,"M");
        }else{
            p.setString(6,"F");
        }
        stmt.setString(2,phone.getText());
            p.setString(5,password.getText());
        }else{
            JOptionPane.showMessageDialog(null,"Passwords are not matching");
        }
        p.executeUpdate();
        stmt.executeUpdate();
        String Uname = username.getText();
        bookdetail bk = new bookdetail();
        bk.odd(Uname); 
        JOptionPane.showMessageDialog(null,"Your Username is "+Uname);
        setVisible(false);
        new logins.Welcome().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new logins.Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMouseClicked
        // TODO add your handling code here:
        Name.setText("");
    }//GEN-LAST:event_NameMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        email.setText("");
    }//GEN-LAST:event_emailMouseClicked

    private void branchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseClicked
        // TODO add your handling code here:
        branch.setText("");
    }//GEN-LAST:event_branchMouseClicked

    private void addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseClicked
        // TODO add your handling code here:
        address.setText("");
    }//GEN-LAST:event_addressMouseClicked

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        // TODO add your handling code here:
        phone.setText("");
    }//GEN-LAST:event_phoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField address;
    private javax.swing.JTextField branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton male;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
