/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;
import javax.swing.*;
import java.awt.Component;
import java.awt.event.*;
import java.sql.*;
import logins.MySqlconnect;

/**
 *
 * @author shadrak
 */
public class bookdetail extends javax.swing.JFrame {
    Connection con = MySqlconnect.ConnectDB();
    /**
     * Creates new form bookdetail
     */
    public bookdetail() {
        initComponents();
    }
    static String uname ;
    public void odd(String name) {
        uname = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookname = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bookname1 = new javax.swing.JTextField();
        author1 = new javax.swing.JTextField();
        price1 = new javax.swing.JTextField();
        condition = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        bookname.setBackground(new java.awt.Color(246, 235, 243));
        bookname.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        bookname.setForeground(new java.awt.Color(28, 18, 18));
        bookname.setText("Name of Book:");
        jPanel1.add(bookname);
        bookname.setBounds(170, 90, 120, 20);

        author.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        author.setText("Name of Author:");
        jPanel1.add(author);
        author.setBounds(150, 140, 140, 18);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel3.setText("Condition:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 240, 90, 21);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 3, 15)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 190, 60, 20);

        title.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        title.setForeground(new java.awt.Color(29, 97, 239));
        title.setText("BOOK DETAILS");
        jPanel1.add(title);
        title.setBounds(200, 20, 240, 40);
        jPanel1.add(bookname1);
        bookname1.setBounds(300, 90, 190, 28);

        author1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author1ActionPerformed(evt);
            }
        });
        jPanel1.add(author1);
        author1.setBounds(300, 130, 190, 28);

        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        jPanel1.add(price1);
        price1.setBounds(300, 180, 120, 28);

        condition.setFont(new java.awt.Font("Century Schoolbook L", 0, 15)); // NOI18N
        condition.setMaximumRowCount(5);
        condition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "New (10)", "Good (7-9)", "Average (4-6)", "Satisfactory ( below 4)", " " }));
        jPanel1.add(condition);
        condition.setBounds(300, 230, 130, 30);

        jButton1.setBackground(new java.awt.Color(79, 237, 31));
        jButton1.setFont(new java.awt.Font("Century Schoolbook L", 0, 15)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 300, 130, 32);

        jButton2.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jButton2.setText("Sell another Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 360, 150, 32);

        jButton3.setBackground(new java.awt.Color(51, 115, 171));
        jButton3.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jButton3.setText("Main Page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 20, 120, 32);

        jButton4.setBackground(new java.awt.Color(218, 85, 43));
        jButton4.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jButton4.setText("Log-out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 30, 100, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void author1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_author1ActionPerformed

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String q = "insert into BOOKS(AUTHOR,TITLE,PRICE,CONDITIONS) values(?,?,?,?)";
        try{
            PreparedStatement p = con.prepareStatement(q,PreparedStatement.RETURN_GENERATED_KEYS);
            //p.setString(1,"5");
            p.setString(1,author1.getText());
            p.setString(2,bookname1.getText());
            p.setString(3,price1.getText());
            p.setString(4,condition.getSelectedItem().toString());
            
            p.executeUpdate();
            ResultSet rs = p.getGeneratedKeys();
            JOptionPane.showMessageDialog(null, "Your Data is Successfully saved.");
            int key = rs.next() ? rs.getInt(1) : 0;
            
            if(key!=0){
                System.out.println("Generated key="+key+"\n"+uname);
            }//setVisible(false);
            //new logins.bookdetail().setVisible(true);
            String s = "insert into BOOKS_RECORD(PERSON,BOOKS) VALUES(?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,uname);
            ps.setInt(2,key);
            ps.executeUpdate();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new logins.Welcome().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new logins.bookdetail().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new logins.Login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookdetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JTextField author1;
    private javax.swing.JLabel bookname;
    private javax.swing.JTextField bookname1;
    private javax.swing.JComboBox<String> condition;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
